opinion_ref_id_tweaks.settings:
  type: config_object
  label: 'Opinion reference ID settings'
  mapping:
    next_number:
      type: integer
      label: 'Next number'
    next_number_year:
      type: integer
      label: 'Next number year'
