<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\taxonomy\TermInterface;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function taxonomy_tweaks_form_taxonomy_term_form_alter(array &$form, FormStateInterface $form_state, string $form_id): void {
  $term = $form_state->getFormObject()->getEntity();
  if (!$term instanceof TermInterface || !$term->isNew()) {
    return;
  }

  $vocabulary = \Drupal::entityTypeManager()->getStorage('taxonomy_vocabulary')->load($term->bundle());
  if (!$vocabulary) {
    return;
  }

  $prefix_map = [
    'legal_entity' => 'Νέος',
  ];

  $prefix = $prefix_map[$term->bundle()] ?? 'Νέα';
  $form['#title'] = t('@prefix @vocabulary', [
    '@prefix' => $prefix,
    '@vocabulary' => $vocabulary->label(),
  ]);
}
