_core:
  default_config_hash: CXhei_vpaZk-3f_Mj2cH0YmpK-ZpKHoSzVA3yZrDq0g
definitions:
  contact__site_page:
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
    enabled: true
  user__page:
    weight: -43
    menu_name: account
    parent: ''
    expanded: false
    enabled: false
  user__logout:
    weight: -40
    menu_name: account
    parent: ''
    expanded: false
    enabled: true
  standard__front_page:
    menu_name: main
    parent: ''
    weight: 0
    expanded: false
    enabled: false
  'admin_toolbar_tools__extra_links:entity__entity_permissions_form__taxonomy_term__default__priority':
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.taxonomy_vocabulary.overview_form.priority'
    weight: 3
    expanded: false
    enabled: false
  'admin_toolbar_tools__extra_links:entity__entity_permissions_form__taxonomy_term__default__tags':
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.taxonomy_vocabulary.overview_form.tags'
    weight: 3
    expanded: false
    enabled: false
  'admin_toolbar_tools__extra_links:entity__entity_permissions_form__taxonomy_term__default__incoming_type':
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.taxonomy_vocabulary.overview_form.incoming_type'
    weight: 3
    expanded: false
    enabled: false
  'admin_toolbar_tools__extra_links:entity__entity_permissions_form__taxonomy_term__default__incoming_subtype':
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.taxonomy_vocabulary.overview_form.incoming_subtype'
    weight: 3
    expanded: false
    enabled: false
  'admin_toolbar_tools__extra_links:entity__entity_permissions_form__taxonomy_term__default__case':
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.taxonomy_vocabulary.overview_form.case'
    weight: 3
    expanded: false
    enabled: false
  'admin_toolbar_tools__extra_links:entity__entity_permissions_form__taxonomy_term__default__legal_entity':
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.taxonomy_vocabulary.overview_form.legal_entity'
    weight: 3
    expanded: false
    enabled: false
