_core:
  default_config_hash: 4GIX5Esnc_umpXUBj4IIocRX7Mt5fPhm4AgXfE3E56E
module:
  activities: 0
  activities_mods: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  amke_access_incoming_by_ref: 0
  amke_tweaks: 0
  automated_cron: 0
  basic_auth: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  case_path_titles: 0
  case_tweaks: 0
  checkbox_radios: 0
  ckeditor5: 0
  ckeditor5_plugin_pack: 0
  ckeditor5_plugin_pack_font: 0
  config: 0
  content_moderation: 0
  contextual: 0
  csv_serialization: 0
  custom_permissions_access: 0
  datetime: 0
  datetime_optional_time: 0
  datetime_range: 0
  dblog: 0
  diff: 0
  dynamic_page_cache: 0
  editor: 0
  entity_browser: 0
  entity_reference_revisions: 0
  entityreference_filter: 0
  field: 0
  field_group: 0
  field_non_empty_lock: 0
  field_permissions: 0
  field_ui: 0
  file: 0
  filter: 0
  greek_holidays: 0
  ief_table_view_mode: 0
  image: 0
  incoming_api: 0
  incoming_change_state: 0
  incoming_create_select_case: 0
  incoming_edit_tweaks: 0
  incoming_form_validations: 0
  incoming_notifications: 0
  incoming_related_field: 0
  incoming_remarks: 0
  incoming_state_validations: 0
  incoming_tweaks: 0
  incoming_views_pdf_tweaks: 0
  inline_entity_form: 0
  jquery_ui: 0
  kemke_breadcrumbs: 0
  kemke_reports: 0
  language: 0
  link: 0
  locale: 0
  menu_link_content: 0
  menu_ui: 0
  mysql: 0
  nocurrent_pass: 0
  node: 0
  node_view_permissions: 0
  notify_widget: 0
  operators_reference_view: 0
  opinion_ref_id_tweaks: 0
  options: 0
  page_cache: 0
  password_policy_character_types: 0
  password_policy_length: 0
  password_policy_username: 0
  path: 0
  path_alias: 0
  pdf_serialization: 0
  permissions_filtering: 0
  reference_table_formatter: 0
  rest: 0
  role_delegation: 0
  search: 0
  select2: 0
  select2_level_class: 0
  serialization: 0
  shortcut: 0
  side_api: 0
  system: 0
  taxonomy: 0
  taxonomy_manager: 0
  taxonomy_tweaks: 0
  text: 0
  toolbar: 0
  user: 0
  user_import: 0
  users_tweaks: 0
  views_autocomplete_filters: 0
  views_bulk_edit: 0
  views_bulk_operations: 0
  views_data_export: 0
  views_tree: 0
  views_ui: 0
  views_year_filters: 0
  workflow_buttons: 0
  workflows: 0
  xls_serialization: 0
  password_policy: 10
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  olivero: 0
  claro: 0
  kemke: 0
profile: standard
