_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: el
uuid: 2caeae2a-70c7-45b8-8506-769378651fe9
name: KEMKE
mail: kongeo@gmail.com
slogan: ''
page:
  403: ''
  404: ''
  front: /user/login
admin_compact_mode: false
weight_select_max: 100
default_langcode: el
mail_notification: null
