objective_1:
  name: 'Στόχος 1 - Γνωμοδοτήσεις'
  description: 'Στόχος 1 - Γνωμοδοτήσεις'
objective_2:
  name: 'Στόχος 2 - Αιτήματα από ιεραρχία'
  description: 'Στόχος 2 - Αιτήματα από ιεραρχία'
objective_3:
  name: 'Στόχος 3 - Κοινοποιήσεις Γνωστοποιήσεiς'
  description: 'Στόχος 3 - Κοινοποιήσεις Γνωστοποιήσεiς'
objective_4:
  name: 'Στόχος 4 - Έκθεση Δαπανών SARI'
  description: 'Στόχος 4 - Έκθεση Δαπανών SARI'
objective_5:
  name: 'Στόχος 5 - Ανάκτηση'
  description: 'Στόχος 5 - Ανάκτηση'
objective_6:
  name: 'Στόχος 6 - Σεμινάρια'
  description: 'Στόχος 6 - Σεμινάρια'
