<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_form_alter().
 */
function incoming_form_validations_form_alter(array &$form, FormStateInterface $form_state, $form_id): void {
  $watchlist = [
    'node_incoming_form',
    'node_incoming_edit_form',
    'node_incoming_revision_edit_form',
    'content_moderation_entity_moderation_form',
  ];

  if (!in_array($form_id, $watchlist, TRUE)) {
    return;
  }

  $entity = $form_state->getFormObject() ? $form_state->getFormObject()->getEntity() : $form_state->get('entity');
  if (!$entity instanceof NodeInterface || $entity->bundle() !== 'incoming') {
    return;
  }

  $form['#attached']['library'][] = 'incoming_form_validations/incoming_form_validations';
}
